### ISSUE TITLE
Stick-ies App - No Note Title

### ISSUE THREAD

**Issue by calireggae** [jsitor/stick-ies#1]
Just purchased the Stick-ies App.  So far, it has everything I want in a stickies/notes app, except it has one major flaw:  there is no way to title each note, separate from the content of the note.  For example, in Outlook's notes, you can give each note a title.  Same for the Stickies app that is native to MacOS.  But with your app, all of the text of the entire note shows up in the darker-colored header bar.  This is very sloppy looking and almost renders the app unusable for me.  I would like to give each app a title, e.g., "Grocery List" or "To Do List".  I don't want the header bar for the note to then also include everything I'm typing in the content of the note, such as "Grocery List Eggs Milk Butter Bread Pasta Apples..." etc.  I'm not a computer programmer but it seems like this should be an easy fix.  If I'm just doing it wrong, please let me know.  If this can be fixed I would give a 5-star review.  Thank you.

**Comment by ashvin777** [comment]
At present you could add a bold title using # or using inline toolbar.

I understood about showing all text in the title bar, we will try to change that.

Thanks for writing to us.

**Comment by ashvin777** [comment]
We have now fixed this issue in our latest version. Request you to uodate that, we have also added multi font support.
