### ISSUE TITLE
Everything in my note was deleted

### ISSUE THREAD

**Issue by moormasi** [jsitor/stick-ies#11]
I tried to expand one of the notes and when I clicked the arrow it wouldn't open. I could see the toolbar at the bottom and even scroll a little bit but it still would not expand. I closed the app and when I restarted it the note expanded but everything I had in that note was deleted, its gone, even after force refresh. Very frustrating.

**Comment by ashvin777** [comment]
We are sorry to hear that. We will look at the issue and will try to resolve. Thank you

**Comment by ashvin777** [comment]
I am now able to reproduce the same, we are soon going to have a fix and release a new version in the app store. Thanks for reporting the issue.

**Comment by ashvin777** [comment]
We have added the option to reset the size and position, this will help to overcome such kind of issues. 

We also improved the undo behaviour to fix the other issue. 

Please update to the latest version.
