### ISSUE TITLE
Collapsed note shows only the toolbar - unable to expand

### ISSUE THREAD

**Issue by larrygarrett** [jsitor/stick-ies#12]
sometimes I click to expand my note, but then all I see is the toolbar and not able to stretch out the note to see the contents.  If I have my mouse, I can control-zoom my way out of it, but can't otherwise.

**Comment by ashvin777** [comment]
Hi @larrygarrett , Thanks for reporting this issue. We have observed similar issue, will try to resolve and push the newer version very soon.

**Comment by ashvin777** [comment]
We have fixed this in our latest version by adding a function to reset the size and position. Please update to the latest version.
