### ISSUE TITLE
Stacking and arranging minimized notes

### ISSUE THREAD

**Issue by johnpaulhadley** [jsitor/stick-ies#13]
It would be incredibly helpful if there was a feature that allowed you to arrange and sort minimized notes. I find myself having to readjust my minimized notes positioning often because they're so easy to slide out of place.

**Comment by ashvin777** [comment]
I hope this is what you are looking for -
![image](https://github.com/jsitor/stick-ies/assets/8143154/aaca6f2b-9abc-4cc3-a0fd-47c45b002809)
