### ISSUE TITLE
Just downloaded and the font and color options don't work.

### ISSUE THREAD

**Issue by Ori4peace** [jsitor/stick-ies#14]
I'm annoyed because I spent money on this app and it does not change my font or change the  color of the font. When typing, it's a generic grey color with a generic font. Please help or return my money. 

Thanks.

**Comment by ashvin777** [comment]
The font and its colors can be easily modified using the bottom toolbar.

**Comment by ashvin777** [comment]
@Ori4peace  can you share some screenshot or video to explain this issue better? We are not seeing any such issue with the app so far.

**Comment by ashvin777** [comment]
We have not observed this issue yet, closing this. Please try our latets update, feel free to open
