### ISSUE TITLE
DELETE NOTES

### ISSUE THREAD

**Issue by Sofysaucedo** [jsitor/stick-ies#17]
How can I remove some notes from my desk?!!

**Comment by ashvin777** [comment]
Regards,AshvinOn 18-Jan-2023, at 3:41 AM, Sofysaucedo ***@***.***> wrote:﻿
How can I remove some notes from my desk?!!

**Comment by ashvin777** [comment]
You can either press Cmd+D or choose "Delete note" option from File menu.
