### ISSUE TITLE
Float a single note

### ISSUE THREAD

**Issue by Peterb999** [jsitor/stick-ies#2]
Really like the look and feel of Stick-ies, but one question: I can bring all notes to the front, but is it possible to keep just one note at the front of all other windows? This is something I can do with the standard Mac Stickies (but that doesn't support markdown!).

Thanks!

**Comment by ashvin777** [comment]
Thanks for the feedback, we are working on adding support for this.

**Comment by ashvin777** [comment]
We have added the support for this functionality in our new version. Please try updating to latest 2.0.1
