### ISSUE TITLE
I can't delete my notes

### ISSUE THREAD

**Issue by anzinne** [jsitor/stick-ies#21]
How can I delete the notes???

**Comment by kemarionscott** [comment]
I'm having the same issue. I haven't quite figured it out yet.

**Comment by ashvin777** [comment]
It can be done either using File menu -
[image: image.png]

Or by pressing Cmd + D key combination. Thanks

**Comment by ashvin777** [comment]
You can press Cmd+D or 
![image](https://github.com/jsitor/stick-ies/assets/8143154/b7b1ba07-351f-4f42-a8b8-f3a4c2d23711)
