### ISSUE TITLE
Not sticking?

### ISSUE THREAD

**Issue by basicchannels** [jsitor/stick-ies#5]
Hi, I just bought your app off the app store however my sticky notes aren't sticking like expected. Please could you let me know how to make them stick, ie float on top of all windows. It's pretty much the only reason I got it. many thanks

**Comment by ashvin777** [comment]
Hi, Could you please describe the issue in detail along with images if you can?

**Comment by ashvin777** [comment]
We have release a new version 2.0.1 today with couple of improvments. Also it add supports for float to top functionality just like native app. Please try, I hope this to resolve your issue
