### ISSUE TITLE
       Font Options

### ISSUE THREAD

**Issue by MDJonas** [jsitor/stick-ies#6]
I just bought Stickies and I can't find where I can change the Font (I see how to change the size, background color, etc.); can it be changed, and if not, please cancel my purchase and refund my payment.  Thank you.

**Comment by ashvin777** [comment]
Hey MDJonas,

Currently we do not support changing the font type, However we will work on it and will have this feature added very soon. 

Regarding reversing the payment, I am not really sure if I can do this, the payment happens via app store and there seems to be no way to reverse the payment.

Regards,
Ashvin

**Comment by MDJonas** [comment]
Just keep the $2, it’s not worth my time to request a refund…

Michael Jonas


You don’t need a parachute to skydive; 
you only need it to skydive twice.

**Comment by ashvin777** [comment]
Hi @MDJonas , We have added this feature now, please update the app to latest. I hope this will be helpful.
