### ISSUE TITLE
Notes on the Stickie dissappeared after hitting "undo" while typing

### ISSUE THREAD

**Issue by MaggieMagnoli** [jsitor/stick-ies#7]
The note was already existing, I was making an edit and adding on to it. While I was typing, I hit "command z" to undo (MAC) and the whole note disappeared so I went to the tool bar to do "edit > undo " then tried "edit >redo" nothing worked. Tried it on another note and the same thing happened. 

I also tried "paste" as I thought maybe the note got copied and nothing was there.

Please help as I had months of planning on that note.

**Comment by ashvin777** [comment]
Sorry to hear that. We will look at the issue. 

Thank you so much for giving us the feedback. 

Regards,
Ashvin

**Comment by MaggieMagnoli** [comment]
Hello,  is there an update on this? or how I could possibly recover the notes that was previously on the stickie that disappeared.

**Comment by ashvin777** [comment]
Hi @MaggieMagnoli , Nope I think that wont be recoverable. We will try to make sure this won't happen again. Our next version will possible have this fix. Thanks

**Comment by ashvin777** [comment]
We have fixed this issue by improving the undo behaviour. Please update to the latest version.
