### ISSUE TITLE
Set default font size

### ISSUE THREAD

**Issue by matpatterson** [jsitor/stick-ies#9]
The default font size is too small for me, so I have to manually increase it every time I create a new note or text block. An option to set a larger default would be helpful.

**Comment by ashvin777** [comment]
Thats a good suggestion, we will try to build some capability to support this. Thanks

**Comment by ashvin777** [comment]
Fyi, this is coming in next update, expected to land in Dec 2023. thanks

**Comment by ashvin777** [comment]
Its now made available with ability to set some preferenes.
